[api]
host = 'localhost'
port = 8000
project_name = 'base'

[database]
host='database'
port=5432
username='postgres'
password='postgres'
database='postgres'

[auth]
private_key_path='src/application/servers/auth/keys/private.pem'
public_key_path='src/application/servers/auth/keys/public.pem'
time=12000
algorithm="RS256"

[data]
user_role_id='user'

[redis]
host = 'redis'
port = 6379
password = redis
