"""roles_elements

Revision ID: 6adab3f9e069
Revises: 6c061abc3214
Create Date: 2026-07-23 13:17:58.774045

"""
from datetime import datetime, timezone
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6adab3f9e069'
down_revision: Union[str, Sequence[str], None] = '6c061abc3214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elements',
    sa.Column('element', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('element'),
    schema='db_schema'
    )
    op.create_table('role_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('element', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('create', sa.Boolean(), nullable=False),
    sa.Column('update', sa.Boolean(), nullable=False),
    sa.Column('get', sa.Boolean(), nullable=False),
    sa.Column('get_all', sa.Boolean(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['element'], ['db_schema.elements.element'], ),
    sa.ForeignKeyConstraint(['role'], ['db_schema.roles.role'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )

    elements_table = sa.table(
        "elements",
        sa.column("element", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
        schema="db_schema",
    )

    roles_elements_table = sa.table(
        "role_elements",
        sa.column("id", sa.UUID()),
        sa.column("element", sa.String()),
        sa.column("role", sa.String()),
        sa.column("create", sa.Boolean()),
        sa.column("update", sa.Boolean()),
        sa.column("get", sa.Boolean()),
        sa.column("get_all", sa.Boolean()),
        sa.column("delete", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
        schema="db_schema",
    )

    now = datetime.now(timezone.utc)
    
    user_elements = "user"
    user_role_elements = "user_role"

    admin_role_id = "admin"
    user_role_id = "user"
    editor_role_id = "editor"

    op.bulk_insert(
        elements_table,
        [
            {
                "element": user_elements,
                "created_at": now,
                "updated_at": now,
            },
            {
                "element": user_role_elements,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )

    op.bulk_insert(
        roles_elements_table,
        [
            {
                "id": uuid.uuid4(),
                "element": user_elements,
                "role": admin_role_id,
                "create": True,
                "update": True,
                "get": True,
                "get_all": True,
                "delete": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "element": user_elements,
                "role": user_role_id,
                "create": True,
                "update": True,
                "get": True,
                "get_all": False,
                "delete": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "element": user_role_elements,
                "role": admin_role_id,
                "create": True,
                "update": True,
                "get": True,
                "get_all": True,
                "delete": True,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )

    

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_elements', schema='db_schema')
    op.drop_table('elements', schema='db_schema')
    # ### end Alembic commands ###
