"""init

Revision ID: 6c061abc3214
Revises: 
Create Date: 2026-07-21 11:01:04.885079

"""
from typing import Sequence, Union
import uuid
from datetime import datetime, timezone, date
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c061abc3214'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='db_schema'
    )
    op.create_table('passwords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['db_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='db_schema'
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['db_schema.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['db_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )

    roles_table = sa.table(
        "roles",
        sa.column("id", sa.UUID()),
        sa.column("name", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
        schema="db_schema",
    )

    users_table = sa.table(
        "users",
        sa.column("id", sa.UUID()),
        sa.column("first_name", sa.String()),
        sa.column("middle_name", sa.String()),
        sa.column("last_name", sa.String()),
        sa.column("email", sa.String()),
        sa.column("birth_date", sa.Date()),
        sa.column("is_active", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
        schema="db_schema",
    )

    passwords_table = sa.table(
        "passwords",
        sa.column("id", sa.UUID()),
        sa.column("user_id", sa.UUID()),
        sa.column("password", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
        schema="db_schema",
    )

    user_roles_table = sa.table(
        "user_roles",
        sa.column("id", sa.UUID()),
        sa.column("user_id", sa.UUID()),
        sa.column("role_id", sa.UUID()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
        schema="db_schema",
    )

    now = datetime.now(timezone.utc)

    admin_role_id = uuid.uuid4()
    user_role_id = uuid.uuid4()
    editor_role_id = uuid.uuid4()

    admin_id = uuid.uuid4()
    user1_id = uuid.uuid4()
    user2_id = uuid.uuid4()
    user3_id = uuid.uuid4()
    user4_id = uuid.uuid4()


    # 1. Роли

    op.bulk_insert(
        roles_table,
        [
            {
                "id": admin_role_id,
                "name": "admin",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": editor_role_id,
                "name": "editor",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": user_role_id,
                "name": "user",
                "created_at": now,
                "updated_at": now,
            },
        ],
    )

    op.bulk_insert(
        users_table,
        [
            {
                "id": admin_id,
                "first_name": "Иван",
                "middle_name": "Иванович",
                "last_name": "Иванов",
                "email": "admin@example.com",
                "birth_date": date(1995, 5, 15),
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": user1_id,
                "first_name": "Анна",
                "middle_name": "Сергеевна",
                "last_name": "Петрова",
                "email": "user1@example.com",
                "birth_date": date(1992, 10, 20),
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": user2_id,
                "first_name": "Владимир",
                "middle_name": "Олегович",
                "last_name": "Юдин",
                "email": "user2@example.com",
                "birth_date": date(2010, 12, 2),
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": user3_id,
                "first_name": "Ирина",
                "middle_name": "Александровна",
                "last_name": "Меньшикова",
                "email": "user3@example.com",
                "birth_date": date(2002, 6, 21),
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": user4_id,
                "first_name": "Дмитрий",
                "middle_name": "Иванович",
                "last_name": "Лебедев",
                "email": "user4@example.com",
                "birth_date": date(2005, 1, 23),
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )


    op.bulk_insert(
        passwords_table,
        [
            {
                "id": uuid.uuid4(),
                "user_id": admin_id,
                "password": "$2b$12$1yENjit5FkM6DxUpsT0oNuXzSK0Zek6x31FWibmygFTcFDRAMqdGu",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "user_id": user1_id,
                "password": "$2b$12$sMz1mWTGtBchBzuAwBf/iO3XEtPrRvGWfQEO757qdWbckAqeB9cJ6",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "user_id": user2_id,
                "password": "$2b$12$cpj6wwwUqfSyuEQVkDi0iOPUmdjXePKnmeTyAyUI3J/GrXXCrg/3u",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "user_id": user3_id,
                "password": "$2b$12$xXJGhD6gUMH/YhUuUCNcBuzeOC/g9Cv8dd64pJ0B2k0yXRSMeZgbG",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "user_id": user4_id,
                "password": "$2b$12$grvNASao7p0QNUhA2Y9i0eVsODFjkNLwQSZnZgniVT6gvVK8b4LSm",
                "created_at": now,
                "updated_at": now,
            }
        ],
    )


    op.bulk_insert(
        user_roles_table,
        [
            {
                "id": uuid.uuid4(),
                "user_id": admin_id,
                "role_id": admin_role_id,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "user_id": user1_id,
                "role_id": editor_role_id,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "user_id": user2_id,
                "role_id": user_role_id,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "user_id": user3_id,
                "role_id": user_role_id,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "user_id": user4_id,
                "role_id": user_role_id,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles', schema='db_schema')
    op.drop_table('passwords', schema='db_schema')
    op.drop_table('users', schema='db_schema')
    op.drop_table('roles', schema='db_schema')
    # ### end Alembic commands ###
