"""products

Revision ID: 51d01ac55f9b
Revises: 6adab3f9e069
Create Date: 2026-07-24 10:57:39.595648

"""
from datetime import datetime, timezone
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d01ac55f9b'
down_revision: Union[str, Sequence[str], None] = '6adab3f9e069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )

    products_table = sa.table(
        "products",
        sa.Column('id', sa.UUID()),
        sa.Column('name', sa.String(length=255)),
        sa.Column('description', sa.Text()),
        sa.Column('price', sa.Float()),
        sa.Column('count', sa.Integer()),
        sa.Column('created_at', sa.DateTime(timezone=True)),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        schema='db_schema'
    )

    
    elements_table = sa.table(
        "elements",
        sa.column("element", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
        schema="db_schema",
    )

    roles_elements_table = sa.table(
        "permission",
        sa.column("id", sa.UUID()),
        sa.column("element", sa.String()),
        sa.column("role", sa.String()),
        sa.column("create", sa.Boolean()),
        sa.column("patch", sa.Boolean()),
        sa.column("get", sa.Boolean()),
        sa.column("get_all", sa.Boolean()),
        sa.column("delete", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
        schema="db_schema",
    )

    now = datetime.now(timezone.utc)
    
    product_elements = "product"

    admin_role_id = "admin"
    user_role_id = "user"
    op.bulk_insert(
        products_table,
        [
            {
                "id": uuid.uuid4(),
                "name": "Шариковая ручка",
                "description": "Синяя шариковая ручка с толщиной линии 0,7 мм",
                "price": 75,
                "count": 100,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "Тетрадь в клетку",
                "description": "Тетрадь формата A5 на 48 листов",
                "price": 120,
                "count": 50,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "Набор цветных карандашей",
                "description": "Набор из 12 цветных карандашей",
                "price": 350,
                "count": 30,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "Блокнот",
                "description": "Блокнот формата A6 на 80 листов в линейку",
                "price": 210,
                "count": 40,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "Текстовый маркер",
                "description": "Жёлтый флуоресцентный маркер со скошенным наконечником",
                "price": 95,
                "count": 70,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )

    op.bulk_insert(
        elements_table,
        [
            {
                "element": product_elements,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )

    op.bulk_insert(
        roles_elements_table,
        [
            {
                "id": uuid.uuid4(),
                "element": product_elements,
                "role": admin_role_id,
                "create": True,
                "patch": True,
                "get": True,
                "get_all": True,
                "delete": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid.uuid4(),
                "element": product_elements,
                "role": user_role_id,
                "create": True,
                "patch": True,
                "get": True,
                "get_all": False,
                "delete": True,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products', schema='db_schema')
    # ### end Alembic commands ###
